baseURL = 'https://tochtli.lapinel-fam.club/'
locale = 'en-us'
title = "Tochtli's Daily Challenges"
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true

sectionPagesMenu = 'main'

[[menu.main]]
identifier = "course"
name = "Course"
url = "course/"
weight = 10

[params]
ShowBreadCrumbs = true
ShowPostNavLinks = true
courseId = "tochtli-june-2026"

[params.profileMode]
enabled = true
title = "Tochtli's Daily Challenges"
subtitle = "Ok, not quite daily but almost"

[[params.profileMode.buttons]]
name = "Week 1"
url = "course/2026/june/week1/"
